server:
  servlet:
    context-path: /api/esport
  port: 8002

spring:
  application.name: esport
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/esport
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none

