INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'af', 'Afghanistan', 'Afghan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'al', 'Albania', 'Albanian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'dz', 'Algeria', 'Algerian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ad', 'Andorra', 'Andorran');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ai', 'Anguilla', 'Angolan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ar', 'Argentina', 'Argentinean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'am', 'Armenia', 'Armenian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'aw', 'Aruba', 'Aruban');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'au', 'Australia', 'Australian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'at', 'Austria', 'Austrian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'az', 'Azerbaijan', 'Azerbaijani');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bs', 'Bahamas', 'Bahamian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bh', 'Bahrain', 'Bahraini');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bd', 'Bangladesh', 'Bangladeshi');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bb', 'Barbados', 'Barbadian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'by', 'Belarus', 'Belarusian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'be', 'Belgium', 'Belgian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bz', 'Belize', 'Belizean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bj', 'Benin', 'Beninese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bm', 'Bermuda', 'Bermudian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bt', 'Bhutan', 'Bhutanese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ba', 'Bosnia and Herzegovina', 'Herzegovinian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'br', 'Brazil', 'Brazilian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bn', 'Brunei Darussalam', 'Bruneian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bg', 'Bulgaria', 'Bulgarian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bf', 'Burkina Faso', 'Burkinabe');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bi', 'Burundi', 'Burundian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'kh', 'Cambodia', 'Cambodian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'cm', 'Cameroon', 'Cameroonian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ca', 'Canada', 'Canadian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'cv', 'Cape Verde', 'Cape Verdean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'cf', 'Central African Republic', 'Central African');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'td', 'Chad', 'Chadian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'cl', 'Chile', 'Chilean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'cn', 'China', 'Chinese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'co', 'Colombia', 'Colombian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'km', 'Comoros', 'Comoran');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'cg', 'Congo', 'Congolese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'cr', 'Costa Rica', 'Costa Rican');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'hr', 'Croatia (Hrvatska)', 'Croatian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'cu', 'Cuba', 'Cuban');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'cy', 'Cyprus', 'Cypriot');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'cz', 'Czech Republic', 'Czech');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'dk', 'Denmark', 'Danish');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'dj', 'Djibouti', 'Djibouti');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'dm', 'Dominica', 'Dominican');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ec', 'Ecuador', 'Ecuadorean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'eg', 'Egypt', 'Egyptian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'sv', 'El Salvador', 'Salvadoran');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'gq', 'Equatorial Guinea', 'Equatorial Guinean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'er', 'Eritrea', 'Eritrean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ee', 'Estonia', 'Estonian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'et', 'Ethiopia', 'Ethiopian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'fj', 'Fiji', 'Fijian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'fi', 'Finland', 'Finnish');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'fr', 'France', 'French');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ga', 'Gabon', 'Gabonese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'gm', 'Gambia', 'Gambian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ge', 'Georgia', 'Georgian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'de', 'Germany', 'German');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'gh', 'Ghana', 'Ghanaian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'gr', 'Greece', 'Greek');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'gd', 'Grenada', 'Grenadian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'gt', 'Guatemala', 'Guatemalan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'gn', 'Guinea', 'Guinean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'gw', 'Guinea-Bissau', 'Guinea-Bissauan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'gy', 'Guyana', 'Guyanese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ht', 'Haiti', 'Haitian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'hn', 'Honduras', 'Honduran');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'hu', 'Hungary', 'Hungarian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'is', 'Iceland', 'Icelander');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'in', 'India', 'Indian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'id', 'Indonesia', 'Indonesian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ir', 'Iran', 'Iranian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'iq', 'Iraq', 'Iraqi');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ie', 'Ireland', 'Irish');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'it', 'Italy', 'Italian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'jm', 'Jamaica', 'Jamaican');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'jp', 'Japan', 'Japanese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'jo', 'Jordan', 'Jordanian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'kz', 'Kazakhstan', 'Kazakhstani');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ke', 'Kenya', 'Kenyan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'kp', 'Korea (North)', 'North Korean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'kr', 'Korea (South)', 'South Korean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'kw', 'Kuwait', 'Kuwaiti');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'kg', 'Kyrgyzstan', 'Kyrgyz');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'la', 'Laos', 'Laotian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'lv', 'Latvia', 'Latvian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'lb', 'Lebanon', 'Lebanese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'lr', 'Liberia', 'Liberian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ly', 'Libya', 'Libyan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'li', 'Liechtenstein', 'Liechtensteiner');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'lt', 'Lithuania', 'Lithuanian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'lu', 'Luxembourg', 'Luxembourger');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'mk', 'Macedonia', 'Macedonian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'mg', 'Madagascar', 'Malagasy');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'mw', 'Malawi', 'Malawian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'my', 'Malaysia', 'Malaysian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'mv', 'Maldives', 'Maldivan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ml', 'Mali', 'Malian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'mt', 'Malta', 'Maltese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'mh', 'Marshall Islands', 'Marshallese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'mr', 'Mauritania', 'Mauritanian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'mu', 'Mauritius', 'Mauritian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'mx', 'Mexico', 'Mexican');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'md', 'Moldova', 'Moldovan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'mc', 'Monaco', 'Monacan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'mn', 'Mongolia', 'Mongolian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ma', 'Morocco', 'Moroccan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'mz', 'Mozambique', 'Mozambican');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'na', 'Namibia', 'Namibian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'nr', 'Nauru', 'Nauruan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'np', 'Nepal', 'Nepalese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'nl', 'Netherlands', 'Dutch');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'nz', 'New Zealand (Aotearoa)', 'New Zealander');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ni', 'Nicaragua', 'Nicaraguan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ne', 'Niger', 'Nigerien');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'no', 'Norway', 'Norwegian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'om', 'Oman', 'Omani');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'pk', 'Pakistan', 'Pakistani');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'pw', 'Palau', 'Palauan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ps', 'Palestinian Territory', 'Palestinian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'pa', 'Panama', 'Panamanian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'pg', 'Papua New Guinea', 'Papua New Guinean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'py', 'Paraguay', 'Paraguayan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'pe', 'Peru', 'Peruvian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'pl', 'Poland', 'Polish');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'pt', 'Portugal', 'Portuguese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'qa', 'Qatar', 'Qatari');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ro', 'Romania', 'Romanian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ru', 'Russian Federation', 'Russian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'rw', 'Rwanda', 'Rwandan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'lc', 'Saint Lucia', 'Saint Lucian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ws', 'Samoa', 'Samoan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'sm', 'San Marino', 'San Marinese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'st', 'Sao Tome and Principe', 'Sao Tomean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'sa', 'Saudi Arabia', 'Saudi');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'sn', 'Senegal', 'Senegalese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'sc', 'Seychelles', 'Seychellois');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'sl', 'Sierra Leone', 'Sierra Leonean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'sg', 'Singapore', 'Singaporean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'sk', 'Slovakia', 'Slovakian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'si', 'Slovenia', 'Slovenian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'sb', 'Solomon Islands', 'Solomon Islander');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'so', 'Somalia', 'Somali');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'za', 'South Africa', 'South African');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'es', 'Spain', 'Spanish');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'lk', 'Sri Lanka', 'Sri Lankan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'sd', 'Sudan', 'Sudanese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'sr', 'Suriname', 'Surinamer');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'sz', 'Swaziland', 'Swazi');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'se', 'Sweden', 'Swedish');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ch', 'Switzerland', 'Swiss');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'sy', 'Syria', 'Syrian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'tw', 'Taiwan', 'Taiwanese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'tj', 'Tajikistan', 'Tajik');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'tz', 'Tanzania', 'Tanzanian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'th', 'Thailand', 'Thai');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'tg', 'Togo', 'Togolese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'to', 'Tonga', 'Tongan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'tt', 'Trinidad and Tobago', 'Trinidadian or Tobagonian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'tn', 'Tunisia', 'Tunisian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'tr', 'Turkey', 'Turkish');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'tm', 'Turkmenistan', 'Turkmen');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'tv', 'Tuvalu', 'Tuvaluan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ug', 'Uganda', 'Ugandan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ua', 'Ukraine', 'Ukrainian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ae', 'United Arab Emirates', 'Emirati');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'us', 'United States of America', 'American');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'uy', 'Uruguay', 'Uruguayan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'uz', 'Uzbekistan', 'Uzbekistani');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 've', 'Venezuela', 'Venezuelan');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'vn', 'Viet Nam', 'Vietnamese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ye', 'Yemen', 'Yemenite');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'zm', 'Zambia', 'Zambian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'zw', 'Zimbabwe', 'Zimbabwean');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bw', 'Botswana', 'Batswana');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'bo', 'Bolivia', 'Bolivian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'gb', 'United Kingdom', 'British');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'mm', 'Myanmar', 'Burmese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'tl', 'Timor-Leste', 'East Timorese');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ph', 'Philippines', 'Filipino');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ci', 'Côte d''Ivoire', 'Ivorian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'fm', 'Micronesia', 'Micronesian');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'ls', 'Lesotho', 'Mosotho');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'vu', 'Vanuatu', 'Ni-Vanuatu');
INSERT INTO country(id, code, name, name_ar) VALUES (gen_random_uuid(), 'rs', 'Serbia', 'Serbian');
